# Generated by Django 4.2.6 on 2024-02-14 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_tag_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='color',
            new_name='code',
        ),
    ]
