# Generated by Django 4.2.6 on 2024-02-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0007_order_paid_order_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
    ]
