# Generated by Django 4.2.10 on 2024-03-23 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0008_alter_order_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_of_available_units',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
