# Generated by Django 4.2.10 on 2024-03-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0011_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
